// <auto-generated />
namespace AMS.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class NewChangesMade : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewChangesMade));
        
        string IMigrationMetadata.Id
        {
            get { return "201309010304486_NewChangesMade"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
